// created by: xu.bw 26.7.5
#include <QDir>
#include <QFile>
#include <QMenu>
#include <QImage>
#include <QStyle>
#include <QEvent>
#include <QLabel>
#include <QAction>
#include <QThread>
#include <QDialog>
#include <QPainter>
#include <QProcess>
#include <QMenuBar>
#include <QFileInfo>
#include <QTextEdit>
#include <QLineEdit>
#include <QSettings>
#include <QCheckBox>
#include <QShortcut>
#include <QtLogging>
#include <QTranslator>
#include <QClipboard>
#include <QStatusBar>
#include <QGridLayout>
#include <QFormLayout>
#include <QTextStream>
#include <QStringView>
#include <QFileDialog>
#include <QHBoxLayout>
#include <QPushButton>
#include <QMessageBox>
#include <QHeaderView>
#include <QMainWindow>
#include <QTableWidget>
#include <QApplication>
#include <QProgressBar>
#include <QDirIterator>
#include <QProgressDialog>
#include <QCoreApplication>
#include <QContextMenuEvent>
#include <QRegularExpression>

#include <qt_windows.h>
